

services:
  nats-server:
    image: nats:latest


  # client-gateway:
  #   build: 
  #     context: ./client-gateway-sf
  #     dockerfile: dockerfile.prod
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - PORT=3000
  #     - NATS_SERVERS=nats://nats-server:4222
    
  business-ms-sf:
    build: 
      context: ./business-ms-sf
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${BUSINESS_DATABASE_URL}
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${BUSINESS_DATABASE_URL}
    depends_on:
      - business-ms-db
  
  business-ms-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_BUSINESS_DB}
    volumes:
      - ./postgres/business-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"